### ISSUE TITLE
101 Visualization: D3

### ISSUE THREAD

**Issue by nbuso** [biojs/edu#17]
slush biojs does not create the file src/index.js stated in the page

**Comment by greenify** [comment]
We are in the process to replace the snipspector tutorial with a simpler one 

http://edu.biojs.net/graduates/basic_io/

Moreover the introduction pages have been extended, so that hopefully it is easier for newcomers to follow the tutorial. 

So the only thing remaining on this issue is an amazing visualization tutorial, which is tracked by #40
